repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-json
    - id: check-added-large-files

- repo: https://github.com/python-poetry/poetry
  rev: 1.6.1
  hooks:
    - id: poetry-check

- repo: https://github.com/sqlfluff/sqlfluff
  rev: 2.3.2
  hooks:
    - id: sqlfluff-lint
      args: [--dialect, ansi]
    - id: sqlfluff-fix
      args: [--dialect, ansi]
